---
- hosts: network
  gather_facts: false
  roles:
    - role: mihudec.net_ansible.routing_bgp
      vars:
        TEMPLATE_ONLY: true
  tasks:
    - name: Verify
      assert:
        that:
          - lookup('file', have_path) == lookup('file', want_path)
      vars: 
        have_path: "{{ TEMPLATE_OUTPUT_DIR }}/{{ inventory_hostname }}_{{ ansible_network_os }}_{{ template_name }}.txt"
        want_path: "results/{{ inventory_hostname }}_{{ ansible_network_os }}_{{ template_name }}.txt"
        template_name: routing_bgp
